// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'api_drink.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

ApiDrink _$ApiDrinkFromJson(Map<String, dynamic> json) => ApiDrink(
  idDrink: json['idDrink'] as String,
  strDrink: json['strDrink'] as String,
  strInstructions: json['strInstructions'] as String,
  strDrinkThumb: json['strDrinkThumb'] as String,
  strDrinkAlternate: json['strDrinkAlternate'] as String?,
  strTags: json['strTags'] as String?,
  strVideo: json['strVideo'] as String?,
  strCategory: json['strCategory'] as String?,
  strIba: json['strIBA'] as String?,
  strAlcoholic: json['strAlcoholic'] as String?,
  strGlass: json['strGlass'] as String?,
  strInstructionsEs: json['strInstructionsES'] as String?,
  strInstructionsDe: json['strInstructionsDE'] as String?,
  strInstructionsFr: json['strInstructionsFR'] as String?,
  strInstructionsIt: json['strInstructionsIT'] as String?,
  strInstructionsZhHans: json['strInstructionsZH-HANS'] as String?,
  strInstructionsZhHant: json['strInstructionsZH-HANT'] as String?,
  strIngredient1: json['strIngredient1'] as String?,
  strIngredient2: json['strIngredient2'] as String?,
  strIngredient3: json['strIngredient3'] as String?,
  strIngredient4: json['strIngredient4'] as String?,
  strIngredient5: json['strIngredient5'] as String?,
  strIngredient6: json['strIngredient6'] as String?,
  strIngredient7: json['strIngredient7'] as String?,
  strIngredient8: json['strIngredient8'] as String?,
  strIngredient9: json['strIngredient9'] as String?,
  strIngredient10: json['strIngredient10'] as String?,
  strIngredient11: json['strIngredient11'] as String?,
  strIngredient12: json['strIngredient12'] as String?,
  strIngredient13: json['strIngredient13'] as String?,
  strIngredient14: json['strIngredient14'] as String?,
  strIngredient15: json['strIngredient15'] as String?,
  strMeasure1: json['strMeasure1'] as String?,
  strMeasure2: json['strMeasure2'] as String?,
  strMeasure3: json['strMeasure3'] as String?,
  strMeasure4: json['strMeasure4'] as String?,
  strMeasure5: json['strMeasure5'] as String?,
  strMeasure6: json['strMeasure6'] as String?,
  strMeasure7: json['strMeasure7'] as String?,
  strMeasure8: json['strMeasure8'] as String?,
  strMeasure9: json['strMeasure9'] as String?,
  strMeasure10: json['strMeasure10'] as String?,
  strMeasure11: json['strMeasure11'] as String?,
  strMeasure12: json['strMeasure12'] as String?,
  strMeasure13: json['strMeasure13'] as String?,
  strMeasure14: json['strMeasure14'] as String?,
  strMeasure15: json['strMeasure15'] as String?,
  strImageSource: json['strImageSource'] as String?,
  strImageAttribution: json['strImageAttribution'] as String?,
  strCreativeCommonsConfirmed: json['strCreativeCommonsConfirmed'] as String?,
  dateModified: json['dateModified'] as String?,
);
