name: mealify_brian_egan
publish_to: none
environment:
  sdk: ^3.9.0
workspace:
  - apps/mealify_app
  - features/drinks/cocktaildb_api_client
  - features/drinks/drinks_database
  - features/drinks/drinks_domain
  - features/drinks/drinks_presentation
  - features/drinks/drinks_repository
  - features/favorites/favorites_database
  - features/favorites/favorites_domain
  - features/favorites/favorites_presentation
  - features/favorites/favorites_repository
  - features/ideas/ideas_presentation
  - features/ingredients/ingredients_domain
  - features/meals/mealdb_api_client
  - features/meals/meals_database
  - features/meals/meals_domain
  - features/meals/meals_presentation
  - features/meals/meals_repository
  - shared/http_client_factory
  - shared/mealify_design_system
  - shared/mealify_localizations
  - shared/query_executor_factory
