name: mealify_app
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none
resolution: workspace

environment:
  sdk: ^3.9.0
  flutter: ^3.35.0

dependencies:
  async:
  bloc:
  cocktaildb_api_client:
    path: ../drinks/cocktaildb_api_client
  drinks_database:
    path: ../drinks/drinks_database
  drinks_domain:
    path: ../drinks/drinks_domain
  drinks_presentation:
    path: ../drinks/drinks_presentation
  drinks_repository:
    path: ../drinks/drinks_repository
  favorites_database:
    path: ../favorites/favorites_database
  favorites_domain:
    path: ../favorites/favorites_domain
  favorites_presentation:
    path: ../favorites/favorites_presentation
  favorites_repository:
    path: ../favorites/favorites_repository
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  go_router:
  http:
  http_client_factory:
    path: ../http_client_factory
  ideas_presentation:
    path: ../ideas/ideas_presentation
  intl: ^0.20.2
  mealdb_api_client:
    path: ../meals/mealdb_api_client
  mealify_design_system:
    path: ../mealify_design_system
  mealify_localizations:
    path: ../mealify_localizations
  meals_database:
    path: ../meals/meals_database
  meals_domain:
    path: ../meals/meals_domain
  meals_presentation:
    path: ../meals/meals_presentation
  meals_repository:
    path: ../meals/meals_repository
  provider:
  query_executor_factory:
    path: ../query_executor_factory

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner:
  flutter_test:
    sdk: flutter
  go_router_builder:
  mocktail: ^1.0.4
  very_good_analysis: ^10.0.0

flutter:
  uses-material-design: true
