name: favorites_list_item
description: Favorites list item RIB — loads and displays a single favorite.
version: 0.1.0+1
publish_to: none
resolution: workspace

environment:
  sdk: ^3.9.0
  flutter: ^3.35.0

dependencies:
  drink:
    path: ../../drinks/drink
  drinks_domain:
    path: ../../drinks/drinks_domain
  favorite:
    path: ../favorite
  favorites_domain:
    path: ../favorites_domain
  flutter:
    sdk: flutter
  meal:
    path: ../../meals/meal
  meals_domain:
    path: ../../meals/meals_domain
  skeletonizer:

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^10.0.0
