import 'dart:convert';

import 'package:mealdb_api_client/mealdb_api_client.dart' as api;
import 'package:mealify_database/mealify_database.dart' as db;

/// Convert a Db Meal to an API Meal
class DbToApiMealConverter extends Converter<api.Meal, db.Meal> {
  /// Construct an object that converts Db Meals to api Meals
  const DbToApiMealConverter();

  @override
  db.Meal convert(api.Meal apiMeal) {
    return db.Meal(
      idMeal: apiMeal.idMeal,
      strMeal: apiMeal.strMeal,
      strMealAlternate: apiMeal.strMealAlternate,
      strCategory: apiMeal.strCategory,
      strArea: apiMeal.strArea,
      strInstructions: apiMeal.strInstructions,
      strMealThumb: apiMeal.strMealThumb,
      strTags: apiMeal.strTags,
      strYoutube: apiMeal.strYoutube,
      strIngredient1: apiMeal.strIngredient1,
      strIngredient2: apiMeal.strIngredient2,
      strIngredient3: apiMeal.strIngredient3,
      strIngredient4: apiMeal.strIngredient4,
      strIngredient5: apiMeal.strIngredient5,
      strIngredient6: apiMeal.strIngredient6,
      strIngredient7: apiMeal.strIngredient7,
      strIngredient8: apiMeal.strIngredient8,
      strIngredient9: apiMeal.strIngredient9,
      strIngredient10: apiMeal.strIngredient10,
      strIngredient11: apiMeal.strIngredient11,
      strIngredient12: apiMeal.strIngredient12,
      strIngredient13: apiMeal.strIngredient13,
      strIngredient14: apiMeal.strIngredient14,
      strIngredient15: apiMeal.strIngredient15,
      strIngredient16: apiMeal.strIngredient16,
      strIngredient17: apiMeal.strIngredient17,
      strIngredient18: apiMeal.strIngredient18,
      strIngredient19: apiMeal.strIngredient19,
      strIngredient20: apiMeal.strIngredient20,
      strMeasure1: apiMeal.strMeasure1,
      strMeasure2: apiMeal.strMeasure2,
      strMeasure3: apiMeal.strMeasure3,
      strMeasure4: apiMeal.strMeasure4,
      strMeasure5: apiMeal.strMeasure5,
      strMeasure6: apiMeal.strMeasure6,
      strMeasure7: apiMeal.strMeasure7,
      strMeasure8: apiMeal.strMeasure8,
      strMeasure9: apiMeal.strMeasure9,
      strMeasure10: apiMeal.strMeasure10,
      strMeasure11: apiMeal.strMeasure11,
      strMeasure12: apiMeal.strMeasure12,
      strMeasure13: apiMeal.strMeasure13,
      strMeasure14: apiMeal.strMeasure14,
      strMeasure15: apiMeal.strMeasure15,
      strMeasure16: apiMeal.strMeasure16,
      strMeasure17: apiMeal.strMeasure17,
      strMeasure18: apiMeal.strMeasure18,
      strMeasure19: apiMeal.strMeasure19,
      strMeasure20: apiMeal.strMeasure20,
      strSource: apiMeal.strSource,
      strImageSource: apiMeal.strImageSource,
      strCreativeCommonsConfirmed: apiMeal.strCreativeCommonsConfirmed,
      dateModified: apiMeal.dateModified,
    );
  }
}

/// Convert an Api Meal to a DB Meal
class ApiToDbMealConverter extends Converter<db.Meal, api.Meal> {
  @override
  api.Meal convert(db.Meal dbMeal) {
    return api.Meal(
      idMeal: dbMeal.idMeal,
      strMeal: dbMeal.strMeal,
      strMealAlternate: dbMeal.strMealAlternate,
      strCategory: dbMeal.strCategory,
      strArea: dbMeal.strArea,
      strInstructions: dbMeal.strInstructions,
      strMealThumb: dbMeal.strMealThumb,
      strTags: dbMeal.strTags,
      strYoutube: dbMeal.strYoutube,
      strIngredient1: dbMeal.strIngredient1,
      strIngredient2: dbMeal.strIngredient2,
      strIngredient3: dbMeal.strIngredient3,
      strIngredient4: dbMeal.strIngredient4,
      strIngredient5: dbMeal.strIngredient5,
      strIngredient6: dbMeal.strIngredient6,
      strIngredient7: dbMeal.strIngredient7,
      strIngredient8: dbMeal.strIngredient8,
      strIngredient9: dbMeal.strIngredient9,
      strIngredient10: dbMeal.strIngredient10,
      strIngredient11: dbMeal.strIngredient11,
      strIngredient12: dbMeal.strIngredient12,
      strIngredient13: dbMeal.strIngredient13,
      strIngredient14: dbMeal.strIngredient14,
      strIngredient15: dbMeal.strIngredient15,
      strIngredient16: dbMeal.strIngredient16,
      strIngredient17: dbMeal.strIngredient17,
      strIngredient18: dbMeal.strIngredient18,
      strIngredient19: dbMeal.strIngredient19,
      strIngredient20: dbMeal.strIngredient20,
      strMeasure1: dbMeal.strMeasure1,
      strMeasure2: dbMeal.strMeasure2,
      strMeasure3: dbMeal.strMeasure3,
      strMeasure4: dbMeal.strMeasure4,
      strMeasure5: dbMeal.strMeasure5,
      strMeasure6: dbMeal.strMeasure6,
      strMeasure7: dbMeal.strMeasure7,
      strMeasure8: dbMeal.strMeasure8,
      strMeasure9: dbMeal.strMeasure9,
      strMeasure10: dbMeal.strMeasure10,
      strMeasure11: dbMeal.strMeasure11,
      strMeasure12: dbMeal.strMeasure12,
      strMeasure13: dbMeal.strMeasure13,
      strMeasure14: dbMeal.strMeasure14,
      strMeasure15: dbMeal.strMeasure15,
      strMeasure16: dbMeal.strMeasure16,
      strMeasure17: dbMeal.strMeasure17,
      strMeasure18: dbMeal.strMeasure18,
      strMeasure19: dbMeal.strMeasure19,
      strMeasure20: dbMeal.strMeasure20,
      strSource: dbMeal.strSource,
      strImageSource: dbMeal.strImageSource,
      strCreativeCommonsConfirmed: dbMeal.strCreativeCommonsConfirmed,
      dateModified: dbMeal.dateModified,
    );
  }
}
