name: drink
description: Drink data provider RIB — fetches and exposes a single Drink.
version: 0.1.0+1
publish_to: none
resolution: workspace

environment:
  sdk: ^3.9.0
  flutter: ^3.35.0

dependencies:
  bloc:
  drinks_domain:
    path: ../drinks_domain
  flutter:
    sdk: flutter
  flutter_bloc:

dev_dependencies:
  bloc_test:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^10.0.0
