name: ideas
description: Ideas RIB — generates meal + drink combo ideas.
version: 0.1.0+1
publish_to: none
resolution: workspace

environment:
  sdk: ^3.9.0
  flutter: ^3.35.0

dependencies:
  async:
  drink:
    path: ../../drinks/drink
  drinks_domain:
    path: ../../drinks/drinks_domain
  favorite:
    path: ../../favorites/favorite
  favorites_domain:
    path: ../../favorites/favorites_domain
  flutter:
    sdk: flutter
  flutter_bloc:
  meal:
    path: ../../meals/meal
  mealify_design_system:
    path: ../../../shared/mealify_design_system
  mealify_localizations:
    path: ../../../shared/mealify_localizations
  meals_domain:
    path: ../../meals/meals_domain
  provider:

dev_dependencies:
  bloc_test:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^10.0.0
