name: favorites_presentation
description: The favorites list and details screens.
version: 0.1.0+1
publish_to: none
resolution: workspace

environment:
  sdk: ^3.9.0
  flutter: ^3.35.0

dependencies:
  bloc:
  drinks_domain:
    path: ../../drinks/drinks_domain
  favorites_domain:
    path: ../favorites_domain
  flutter:
    sdk: flutter
  flutter_bloc:
  mealify_design_system:
    path: ../../../shared/mealify_design_system
  mealify_localizations:
    path: ../../../shared/mealify_localizations
  meals_domain:
    path: ../../meals/meals_domain
  provider:
  skeletonizer:

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^10.0.0
