name: cocktaildb_api_client
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none
resolution: workspace

environment:
  sdk: ^3.9.0

dependencies:
  http:
  http_status:
  meta:

dev_dependencies:
  http_client_factory:
    path: ../../http_client_factory
  mocktail: ^1.0.4
  test: ^1.26.3
  very_good_analysis: ^10.0.0
