name: mealify_app
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none
resolution: workspace

environment:
  sdk: ^3.9.0
  flutter: ^3.35.0

dependencies:
  async:
  bloc:
  drink_details:
    path: ../../features/drinks/drink_details
  drinks_data:
    path: ../../features/drinks/drinks_data
  drinks_domain:
    path: ../../features/drinks/drinks_domain
  favorite_details:
    path: ../../features/favorites/favorite_details
  favorites_data:
    path: ../../features/favorites/favorites_data
  favorites_domain:
    path: ../../features/favorites/favorites_domain
  favorites_list:
    path: ../../features/favorites/favorites_list
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  go_router:
  http:
  http_client_factory:
    path: ../../shared/http_client_factory
  ideas:
    path: ../../features/ideas/ideas
  intl: ^0.20.2
  meal_details:
    path: ../../features/meals/meal_details
  mealify_design_system:
    path: ../../shared/mealify_design_system
  mealify_localizations:
    path: ../../shared/mealify_localizations
  meals_data:
    path: ../../features/meals/meals_data
  meals_domain:
    path: ../../features/meals/meals_domain
  provider:
  query_executor_factory:
    path: ../../shared/query_executor_factory

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner:
  flutter_test:
    sdk: flutter
  go_router_builder:
    git:
      url: https://github.com/brianegan/packages.git
      path: packages/go_router_builder
      ref: 9f77d60918e6f7b532e515db09d84f2da8bc6555
  mocktail: ^1.0.4
  very_good_analysis: ^10.0.0

flutter:
  uses-material-design: true
