name: mealify_app
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none
resolution: workspace

environment:
  sdk: ^3.9.0
  flutter: ^3.35.0

dependencies:
  async:
  bloc:
  drinks_data:
    path: ../../features/drinks/drinks_data
  drinks_domain:
    path: ../../features/drinks/drinks_domain
  drinks_presentation:
    path: ../../features/drinks/drinks_presentation
  favorites_data:
    path: ../../features/favorites/favorites_data
  favorites_domain:
    path: ../../features/favorites/favorites_domain
  favorites_presentation:
    path: ../../features/favorites/favorites_presentation
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  go_router:
  http:
  http_client_factory:
    path: ../../shared/http_client_factory
  ideas_presentation:
    path: ../../features/ideas/ideas_presentation
  intl: ^0.20.2
  mealify_design_system:
    path: ../../shared/mealify_design_system
  mealify_localizations:
    path: ../../shared/mealify_localizations
  meals_data:
    path: ../../features/meals/meals_data
  meals_domain:
    path: ../../features/meals/meals_domain
  meals_presentation:
    path: ../../features/meals/meals_presentation
  provider:
  query_executor_factory:
    path: ../../shared/query_executor_factory

dev_dependencies:
  bloc_test: ^10.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^10.0.0

flutter:
  uses-material-design: true
