name: Monorepo Build

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    paths:
      - "apps/**"
      - "features/**"
      - "shared/**"
      - ".github/workflows/monorepo_build.yaml"

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      flutter_version: ${{ steps.read_fvm.outputs.version }}
    steps:
      - uses: actions/checkout@v4
      - id: read_fvm
        name: Extract Version from .fvmrc
        run: |
          VERSION=$(jq -r .flutter .fvmrc)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

  verify_and_test:
    name: Verify and Test
    needs: setup
    strategy:
      fail-fast: false
      matrix:
        package:
          - apps/mealify_app
          - features/drinks/cocktaildb_api_client
          - features/drinks/drinks_database
          - features/drinks/drinks_presentation
          - features/drinks/drinks_repository
          - features/favorites/favorites_database
          - features/favorites/favorites_presentation
          - features/favorites/favorites_repository
          - features/ideas/ideas_presentation
          - features/meals/mealdb_api_client
          - features/meals/meals_database
          - features/meals/meals_repository

    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      flutter_version: ${{ needs.setup.outputs.flutter_version }}
      working_directory: ${{ matrix.package }}
      coverage_excludes: "**/*.g.dart"
      # I know I'm naughty, but 100% coverage wasn't helpful to this learning exercise 🙈
      min_coverage: 0
